Fix fzf_binary_preview command for fish shell
yuki-yano/fzf-preview.vim pull request #220
Opened 2021-01-11 09:31 UTC by eddyekofo94

Some auto formatting on the README but it shouldn't be too bad.
 fixes the #124

2021-01-15 00:38 UTC, yuki-ycino commented
The docs and settings are too complicated, so I think the current situation is fine.
Are the tips in the README insufficient?

```
set shell=/bin/zsh
let $SHELL = "/bin/zsh"
```

2021-01-18 08:08 UTC, judewang commented
I found something weird. If I set let up fzf-preview by adding this line:

```vim
g:fzf_preview_if_binary_command = "test (file -b --mime-encoding {}) = 'binary'"
```

I got a very short loading time when trying moving cursor to switch between files and previewed the source code. 

![CleanShot 2021-01-18 at 17 04 30](https://user-images.githubusercontent.com/1559819/104887879-58dd9e80-59af-11eb-9dc8-7858e935c766.gif)

But by setting up the other way:

```vim
if executable('fish')
    set shell=fish
    let $SHELL="zsh
endif
```

I got no loading time when moving cursor between file names and still can have fish as my internal shell.

2021-01-26 05:16 UTC, eddyekofo94 commented
@yuki-yano well I believe it is better to have it working straight out of the box, plus setting fish as my default shell breaks some other configs.

2021-02-01 04:29 UTC, yuki-yano commented
Sorry for the delay in replying.

I understand, I will try to incorporate this change.
Can you add a note about the change in the doc as well?

Also, is it necessary to add line breaks?
As long as I'm using markdownlint, it doesn't seem to be a problem.

2021-02-03 06:09 UTC, yuki-yano requested changes

2021-02-03 06:09 UTC, yuki-yano commented on plugin/fzf_preview.vim
> +  if executable('fish')
```suggestion
  if executable('fish') && &shell ==# 'fish'
```

2021-06-23 11:42 UTC, closed without merging